name: Deploy to server

on:
  - push

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
      - name: INSTALAR DEPENDENCIAS
        run: echo "INSTALANDO DEPENDENCIAS ..."

  deploy:
    runs-on: ubuntu-latest
    needs: set-up

    steps:
      - name: Hola Mundo
        run: echo "HOLA MUNDO"