name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: Setup Ssh
       uses: webfactory/ssh-agent@v0.9.0
       with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

     - name: Create file
       run: bash deploy.sh
