name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: setup
       run: ls -al